cmake_minimum_required(VERSION 4.1)
project(algorithms)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_subdirectory(contest_1)
add_subdirectory(contest_2)
add_subdirectory(contest_3)
add_subdirectory(contest_4)
add_subdirectory(contest_5)
add_subdirectory(contest_6)
add_subdirectory(contest_7)
add_subdirectory(contest_8)
add_subdirectory(contest_9)
add_subdirectory(contest_10)
add_subdirectory(control_work)
